version: "3.8"

services:
  # Service MongoDB
  mongodb:
    image: mongo:5
    restart: always
    volumes:
      - ${MONGO_DATA_PATH:-./mongo_data}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - app_network

  # Service Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/burn?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      MOODLE_BASE_URL: https://universitice.univ-rouen.fr/
      FRONTEND_URL: ${FRONTEND_URL}
      CAS_BASE_URL: https://cas.univ-rouen.fr/
      MOBILE_URLSCHEME: moodlemobile
    ports:
      - "3000:3000"
    networks:
      - app_network

  # Service Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_API_ENDPOINT=${API_URL}
        - API_URL=${API_URL}
    restart: always
    ports:
      - "1234:80"
    depends_on:
      - backend
    networks:
      - app_network

# Volumes persistants
volumes:
  # mongodb_data volume removed; using bind mount instead

# Réseau partagé entre les conteneurs
networks:
  app_network:
    driver: bridge
