FROM node:18-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json
COPY server/package*.json ./

# Installer seulement les dépendances de production
RUN npm ci --only=production

# Copier le reste des fichiers du backend
COPY server/ ./

# Définir l'environnement de production
ENV NODE_ENV=production

# Exposer le port 3000
EXPOSE 3000

# Commande pour démarrer l'application
CMD ["node", "index.js"]